### PR TITLE
Use Fabric's world load event.

### LINKED ISSUE #148: Patchwork API incompatible with Fabric API versions ≥0.15.0
As of posting, this incompatibility refers to Fabric API v0.15.0 and v0.15.1 for 1.14.4. Tested against both the release v0.7.0 and commit 494fd271bd27556595545e4f34ecb013127701d3.

Crash log: https://pastebin.com/GxWdzDB1

The problem appears to be a redirect conflict between the new Fabric Lifecycle Events V1 and Patchwork API. 

For reference, here are the conflicting redirects (I believe):

https://github.com/FabricMC/fabric/blob/3673fdf545ad946a8a1cba5e6c5fcdfa88d50900/fabric-lifecycle-events-v1/src/main/java/net/fabricmc/fabric/mixin/event/lifecycle/MinecraftServerMixin.java#L94

https://github.com/PatchworkMC/patchwork-api/blob/494fd271bd27556595545e4f34ecb013127701d3/patchwork-events-world/src/main/java/net/patchworkmc/mixin/event/world/MixinMinecraftServer.java#L80

### PR DESCRIPTION
**Pull request by kitlith**
Fixes #148.

Minor point of discussion: how much do we care about the overworld event being fired earlier than Forge does it? I've separated out the workaround for that into the second commit, so that can easily be removed if we want.

### CODE REVIEW

File: patchwork-events-world/src/main/java/net/patchworkmc/mixin/event/world/MixinMinecraftServer.java [hunk 1]
```diff
@@ -47,42 +48,10 @@ public MixinMinecraftServer(String name) {
...
-
-	// This injection handles every other dimension type.
-	@Redirect(method = "createWorlds", at = @At(value = "INVOKE", target = "java/util/Map.put (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", ordinal = 1))
-	private Object proxyPutWorld(Map<Object, Object> worlds, Object type, Object world) {
-		worlds.put(type, world);
-		WorldEvents.onWorldLoad((ServerWorld) world);
-
-		return world;
+	// Fabric usually fires the event much earlier in the method, so this is just picking a point closer to when Forge would fire it.
+	@Inject(method = "createWorlds", at = @At(value = "INVOKE", target = "net/minecraft/world/dimension/DimensionType.getAll ()Ljava/lang/Iterable;"))
```
Comment (i509VCB) [inline patchwork-events-world/src/main/java/net/patchworkmc/mixin/event/world/MixinMinecraftServer.java:52]: Shouldn't the inject target be in `Lnet/minecraft/whatever` format?

Comment (kitlith) [reply patchwork-events-world/src/main/java/net/patchworkmc/mixin/event/world/MixinMinecraftServer.java:52]: hm. good question, and i hope i haven't goofed my previous PRs because of this. I've just been copying from IDEA's bytecode viewer: `INVOKESTATIC net/minecraft/world/dimension/DimensionType.getAll ()Ljava/lang/Iterable;`

Comment (kitlith) [reply patchwork-events-world/src/main/java/net/patchworkmc/mixin/event/world/MixinMinecraftServer.java:52]: Well, it at least seems to work as intended as-is. I'll leave "should it be changed anyway" as something for future consideration.

Comment (TheGlitch76) [reply patchwork-events-world/src/main/java/net/patchworkmc/mixin/event/world/MixinMinecraftServer.java:52]: i con't care about the signature format as long as it's readable and it applies
